### ISSUE TITLE
stateoverride for pre_traceMany

### ISSUE THREAD

**Issue by huahuayu** [DeBankDeFi/go-ethereum-debank#4]
# Rationale

I found that `pre_traceMany` don't support state override, which is a useful feature missed.

You can see that geth eth_call/ traceCall all support state override.

With state override, you can e.g. override erc20 approve state before trace, so you don't really have to approve in advance.

# Implementation

[Geth TraceCallConfig](https://github.com/ethereum/go-ethereum/blob/6e934f40f9a7edd58107725d9d766770bc128775/eth/tracers/api.go#L164)

**Comment by recursion128** [comment]
This is a very meaningful feature, I'll implement it.

**Comment by recursion128** [comment]
Done

**Comment by huahuayu** [comment]
The code is updated, but there's no [document](https://github.com/DeBankDeFi/go-ethereum-debank/blob/32e328be393dae42dda143eeff96c371622c3fbf/docs/features/EVM%20Pre%20Execution.md?plain=1#L34) update or new test added.
